"""Remove E2EE master key fields from users table

Revision ID: 05c95fbafe11
Revises: add_e2ee_master_key
Create Date: 2026-05-12 00:19:45.597988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05c95fbafe11'
down_revision: Union[str, Sequence[str], None] = 'add_e2ee_master_key'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'master_key_salt')
    op.drop_column('users', 'encrypted_master_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('encrypted_master_key', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('master_key_salt', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
