"""Hash refresh tokens for security

Revision ID: 063984bd2930
Revises: e2d733be778b
Create Date: 2026-05-07 14:14:14.445792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '063984bd2930'
down_revision: Union[str, Sequence[str], None] = 'e2d733be778b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add new columns first (allowing NULL temporarily)
    op.add_column('refresh_tokens', sa.Column('token_hash', sa.String(), nullable=True))
    op.add_column('refresh_tokens', sa.Column('token_jti', sa.String(), nullable=True))
    
    # Migrate existing data from plain tokens to hashed tokens
    connection = op.get_bind()
    
    # Import required modules for data migration
    import os
    import jwt
    from argon2 import PasswordHasher
    
    # Initialize password hasher
    ph = PasswordHasher()
    
    # Get all existing refresh tokens
    result = connection.execute(sa.text("SELECT id, token FROM refresh_tokens"))
    existing_tokens = result.fetchall()
    
    # Migrate each token
    for token_id, plain_token in existing_tokens:
        try:
            # Hash the token
            token_hash = ph.hash(plain_token)
            
            # Extract JTI from token
            payload = jwt.decode(plain_token, os.getenv("JWT_SECRET_KEY"), algorithms=["HS256"])
            token_jti = payload.get("jti")
            
            # Update the record with hashed values
            connection.execute(
                sa.text("""
                    UPDATE refresh_tokens 
                    SET token_hash = :token_hash, token_jti = :token_jti
                    WHERE id = :token_id
                """),
                {
                    "token_hash": token_hash,
                    "token_jti": token_jti,
                    "token_id": token_id
                }
            )
        except Exception as e:
            print(f"Error migrating token {token_id}: {e}")
            continue
    
    # Now make the new columns NOT NULL
    op.alter_column('refresh_tokens', 'token_hash', nullable=False)
    op.alter_column('refresh_tokens', 'token_jti', nullable=False)
    
    # Drop old unique constraint and column
    op.drop_constraint(op.f('refresh_tokens_token_key'), 'refresh_tokens', type_='unique')
    op.create_unique_constraint('uq_refresh_tokens_token_hash', 'refresh_tokens', ['token_hash'])
    op.create_unique_constraint('uq_refresh_tokens_token_jti', 'refresh_tokens', ['token_jti'])
    op.drop_column('refresh_tokens', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'refresh_tokens', type_='unique')
    op.drop_constraint(None, 'refresh_tokens', type_='unique')
    op.create_unique_constraint(op.f('refresh_tokens_token_key'), 'refresh_tokens', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_column('refresh_tokens', 'token_jti')
    op.drop_column('refresh_tokens', 'token_hash')
    # ### end Alembic commands ###
