"""remove_device_fingerprint_from_persistent_refresh_tokens

Revision ID: 4cc8051dfd61
Revises: a7102a20d05a
Create Date: 2026-05-07 18:20:21.916489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cc8051dfd61'
down_revision: Union[str, Sequence[str], None] = 'a7102a20d05a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persistent_refresh_tokens', 'device_fingerprint')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persistent_refresh_tokens', sa.Column('device_fingerprint', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
