"""Update persistent refresh tokens to use Argon2ID

Revision ID: a7102a20d05a
Revises: 063984bd2930
Create Date: 2026-05-07 14:25:22.117259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7102a20d05a'
down_revision: Union[str, Sequence[str], None] = '063984bd2930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
