"""Add E2EE master key fields to users table

Revision ID: add_e2ee_master_key
Revises: 4cc8051dfd61
Create Date: 2026-05-10 11:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_e2ee_master_key'
down_revision: Union[str, Sequence[str], None] = '4cc8051dfd61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('encrypted_master_key', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('master_key_salt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'master_key_salt')
    op.drop_column('users', 'encrypted_master_key')
    # ### end Alembic commands ###
