"""Add persistent refresh tokens table

Revision ID: e2d733be778b
Revises: 4e2962b14148
Create Date: 2026-05-07 12:25:10.717133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2d733be778b'
down_revision: Union[str, Sequence[str], None] = '4e2962b14148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persistent_refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('device_fingerprint', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_ip_address_blocked_expires_at'), table_name='ip_address_blocked')
    op.drop_index(op.f('ix_ip_address_blocked_ip_address'), table_name='ip_address_blocked')
    op.drop_index(op.f('ix_ip_address_blocked_is_active'), table_name='ip_address_blocked')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ip_address_blocked_is_active'), 'ip_address_blocked', ['is_active'], unique=False)
    op.create_index(op.f('ix_ip_address_blocked_ip_address'), 'ip_address_blocked', ['ip_address'], unique=False)
    op.create_index(op.f('ix_ip_address_blocked_expires_at'), 'ip_address_blocked', ['expires_at'], unique=False)
    op.drop_table('persistent_refresh_tokens')
    # ### end Alembic commands ###
