"""Remove user_id from ip_address_blocked table

Revision ID: 4e2962b14148
Revises: 5ac556091431
Create Date: 2026-05-07 10:37:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e2962b14148'
down_revision: Union[str, Sequence[str], None] = '5ac556091431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the foreign key constraint first
    op.drop_constraint('ip_address_blocked_user_id_fkey', 'ip_address_blocked', type_='foreignkey')
    # Then drop the column
    op.drop_column('ip_address_blocked', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column back
    op.add_column('ip_address_blocked', sa.Column('user_id', sa.UUID(), nullable=True))
    # Add the foreign key constraint back
    op.create_foreign_key('ip_address_blocked_user_id_fkey', 'ip_address_blocked', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
